services:
  worker:
    image: apache/airflow:3.2.0
    container_name: airflow-worker
    command: celery worker
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW__CELERY__RESULT_BACKEND}
      AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW__CELERY__BROKER_URL}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CELERY__WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-2}
      DUMB_INIT_SETSID: "0"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CSV_PATH: /opt/airflow/data/new_data/sales_data_sample.csv
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
      - ../sql:/opt/airflow/sql
      - ../outputs:/opt/airflow/outputs
      - ../airflow/logs:/opt/airflow/logs
    user: "${AIRFLOW_UID:-50000}:0"
    restart: always
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
