services:
  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.2.1
    container_name: airflow-git-sync
    user: "0:0"
    env_file:
      - .env
    environment:
      GITSYNC_REPO: ${GIT_REPO_URL}
      GITSYNC_BRANCH: ${GIT_BRANCH:-main}
      GITSYNC_ROOT: /git
      GITSYNC_LINK: current
      GITSYNC_PERIOD: ${GIT_SYNC_PERIOD:-60s}
      GITSYNC_DEPTH: 1
    volumes:
      - dags-volume:/git
    restart: always

  worker:
    build: .
    image: airflow-worker-custom:latest
    container_name: airflow-worker
    command: celery worker -q ${QUEUES:-celery} -H ${CELERY_HOSTNAME:-worker}@%h
    env_file:
      - .env
    volumes:
      - dags-volume:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config
      - /home/ubuntu/.ssh:/opt/airflow/.ssh:ro
      - /home/ubuntu/pipeline/worker/dbt:/opt/airflow/.dbt:ro
    user: "${AIRFLOW_UID:-50000}:0"
    restart: always
    depends_on:
      git-sync:
        condition: service_started
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s

volumes:
   dags-volume: